git:
  tagName: 'v${version}'
  commitMessage: 'Release version ${version}'

github:
  release: true
  assets:
    - mathquill4quill.js
    - mathquill4quill.min.js
  preRelease: true

npm:
  release: false

hooks:
  before:init:
    - npm run lint
